language: cpp

dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libgtest-dev

before_install:
- export CC=gcc-7
- export CXX=g++-7

before_script:
- nproc
- which cmake

- mkdir /tmp/gtest
- env -C /tmp/gtest cmake /usr/src/googletest -DCMAKE_CXX_FLAGS=-std=c++11 -Dgtest_disable_pthreads=1
- env -C /tmp/gtest make -j $(nproc)
- env -C /tmp/gtest sudo make install

script:
- ./configure --examples --tests --benchmarks
- make -j $(nproc)
- make test
