language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

before_install:
- sudo apt update
- sudo apt install -y libgtest-dev
- export CC=gcc-5
- export CXX=g++-5
